site_name: My Docs
site_description: "My docs desc"
site_author: "sunshine-grace"

plugins:
  - search
  - awesome-pages
  # - pdf-export
  # - autolinks
nav:
  - 'Welcome': "index.md"
  - 'Getting Started':
    - '主题': 'main.md'
    - '关于': 'about.md'

repo_url: https://github.com/sunshine-grace/mkdocstest.git
repo_name: "mkdocstest"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate # 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  i18n:
    prev: 'Previous'
    next: 'Next'
